CREATE PROCEDURE [dbo].[SPDeleteStudyProgram]
	@studyId int
AS
BEGIN TRANSACTION
BEGIN TRY
	DECLARE @ROWS INT;
	DELETE FROM StudyPrograms
	WHERE StudyProgramID = @studyId
	SET @ROWS = @@ROWCOUNT;
COMMIT TRANSACTION
END TRY

BEGIN CATCH
	ROLLBACK TRANSACTION
END CATCH
RETURN @ROWS
