/*
	Delete a course
*/
CREATE PROCEDURE [dbo].[SPDeleteCourse]
	@courseId INT
AS
BEGIN TRANSACTION
BEGIN TRY
	DECLARE @ROWS INT;
	DELETE FROM Courses
	WHERE CourseID = @courseId
	SET @ROWS = @@ROWCOUNT;
COMMIT TRANSACTION
END TRY

BEGIN CATCH
	ROLLBACK TRANSACTION
END CATCH
RETURN @ROWS
